### ISSUE TITLE
How to get STIP feature

### ISSUE THREAD

**Issue by kaiqiangh** [Spareman/Action-recognition-BagOfWords-Early-Late-Fusion#1]
Hi Manolish,

Thanks for sharing. I would wonder how to get STIP feature from videos. I did not find any open source codes, which can extract STIP. Any tips for that? Thanks in advance.

Kind regards.
Kaiqiang

**Comment by Spareman** [comment]
Sorry for the (very) late response. The STIP features were included in the dataset, therefore there was no need for me to extract.
Sorry that I cannot help you more with that.
